//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_leer
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnose
    {
        public int PK_Diagnose { get; set; }
        public Nullable<System.DateTime> Diagnosezeitpunkt { get; set; }
        public string Diagnosestatus { get; set; }
        public Nullable<int> FK_Krankheit { get; set; }
        public Nullable<int> FK_Patient { get; set; }
    
        public virtual krankheit krankheit { get; set; }
        public virtual patient patient { get; set; }
    }
}
