//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_leer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class krankenhausEntities1 : DbContext
    {
        public krankenhausEntities1()
            : base("name=krankenhausEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abteilung> abteilung { get; set; }
        public virtual DbSet<beruf> beruf { get; set; }
        public virtual DbSet<diagnose> diagnose { get; set; }
        public virtual DbSet<gebaeude> gebaeude { get; set; }
        public virtual DbSet<gehalt> gehalt { get; set; }
        public virtual DbSet<krankenkassenkarte> krankenkassenkarte { get; set; }
        public virtual DbSet<krankheit> krankheit { get; set; }
        public virtual DbSet<mitarbeiter> mitarbeiter { get; set; }
        public virtual DbSet<ort> ort { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<raum> raum { get; set; }
        public virtual DbSet<schichtplan> schichtplan { get; set; }
        public virtual DbSet<schichttyp> schichttyp { get; set; }
        public virtual DbSet<termin> termin { get; set; }
    }
}
