//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_leer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mitarbeiter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mitarbeiter()
        {
            this.schichtplan = new HashSet<schichtplan>();
        }
    
        public int PK_Mitarbeiter { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public Nullable<System.DateTime> Geburtsdatum { get; set; }
        public string E_Mail { get; set; }
        public string Passwort { get; set; }
        public Nullable<long> Telefonnummer { get; set; }
        public string Straße { get; set; }
        public Nullable<int> Hausnummer { get; set; }
        public Nullable<int> FK_Beruf { get; set; }
        public Nullable<int> FK_Gehalt { get; set; }
        public Nullable<int> FK_Ort { get; set; }
    
        public virtual beruf beruf { get; set; }
        public virtual gehalt gehalt { get; set; }
        public virtual ort ort { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schichtplan> schichtplan { get; set; }
    }
}
