//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_leer
{
    using System;
    using System.Collections.Generic;
    
    public partial class schichtplan
    {
        public int PK_Schichtplan { get; set; }
        public Nullable<System.TimeSpan> Schichtbeginn { get; set; }
        public Nullable<System.TimeSpan> Schichtende { get; set; }
        public Nullable<int> FK_Schichttyp { get; set; }
        public Nullable<int> FK_Mitarbeiter { get; set; }
    
        public virtual mitarbeiter mitarbeiter { get; set; }
        public virtual schichttyp schichttyp { get; set; }
    }
}
