//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_leer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_verkauf
    {
        public string ean { get; set; }
        public float preis { get; set; }
        public string vertrieb { get; set; }
        public int id_album { get; set; }
    
        public virtual tbl_album tbl_album { get; set; }
    }
}
